### ISSUE TITLE
How to run on flink 1.14.5？

### ISSUE THREAD

**Issue by yh-rgb** [getindata/flink-http-connector#18]
Is any idea to run on 1.14.5,  is it possible to downgrade some of the used apis?

**Comment by maver1ck** [comment]
Hi @yh-rgb,
We based our sink on Async Sink API, which was introduced in 1.15.
https://cwiki.apache.org/confluence/display/FLINK/FLIP-171%3A+Async+Sink
So unfortunately downgrade would need rewrite everything.

**Comment by kristoffSC** [comment]
In fact it is not possible to replicate some features of Http Sink on 1.14 - for example Sink Async support that is crucial for HTTP clients was added to Flink in 1.15 and its based on batching, where Flink call Sink API with collection of events to process. 
Those events were buffered by Flink - again not supported in 1.14 unless you would use Windows.

Also we don't want to use @Internal API of Flink.
