### ISSUE TITLE
What's the meaning of ESP-xx in git message?

### ISSUE THREAD

**Issue by ChengkaiYang2022** [getindata/flink-http-connector#31]
Hi, I like your work here!

I find that you list some interesting TODOs in the [README.md](https://github.com/getindata/flink-http-connector/tree/6a2846fe8a433b2d44ba95a2f640ab769ed7b4f6#readme) page , and I want to contribute some help to this repository. Actually, I tried to do my own version of flink-http-connector last months ago, but I only finished [table sink part](https://github.com/ChengkaiYang2022/flink-connector-http). I guess it would be better for me to contribute in this project, instead of working on my own project, since you already did so many amazing works!

Anyway, I note that you used ESP-98-xxx in the git message, is ESP-98-xxx like a JIRA issue of this project? (Like [Apache Flink ](https://github.com/apache/flink) use FLINK-19999 in their git message to link the JIRA issue)?
Would you mind to share the details about these ESP ? Or is there a JIRA page for this project that I can learn more about the history of this project?

**Comment by ChengkaiYang2022** [comment]
Ok, I notice that there are some descriptions and discussion under the [PR](https://github.com/getindata/flink-http-connector/pull/21).

Anyway, just wonder, what ESP stand for? :)

**Comment by kristoffSC** [comment]
Hi @ChengkaiYang2022 
I very happy to see you being interested with our little project here :) 

I will give you more info on Monday, now just want to say "welcome" :)

**Comment by ChengkaiYang2022** [comment]
@kristoffSC sorry for the late check. Thanks for the reply!. I get the meaning of 'ESP' after the reading the comments.

Anyway, I agree with the idea that using "Github issues" to drive development and using '[HTTP-xxx]' in the git message to address the github issue.

And I like the idea of creating github firstly and beginning with discussion, just like the Apache brief "Community over code".

Okay, I will check more details of this project and try to get a better understanding of "Flink's 1.15 Async Sink." firstly.

Anyway, It's so nice to find this project!
