### ISSUE TITLE
setElementConverter for HttpSinkRequestEntry is deprecated ,what is alternate method or code we need to use 

### ISSUE THREAD

**Issue by someshwar1** [getindata/flink-http-connector#61]
@Deprecated
@PublicEvolving
public HttpSinkBuilder<InputT> setElementConverter(ElementConverter<InputT, HttpSinkRequestEntry> elementConverter) {
  this.elementConverter = elementConverter;
  return this;
}

code :
HttpSink.<String>builder()
      .setEndpointUrl("http://example.com/myendpoint")
      .setElementConverter(
          (s, _context) -> new HttpSinkRequestEntry("POST", s.getBytes(StandardCharsets.UTF_8)))
      .setProperty("gid.connector.http.sink.header.X-Content-Type-Options", "nosniff")
      .build();

**Comment by kristoffSC** [comment]
Hi,
thanks for the question. Please use `setElementConverter(SchemaLifecycleAwareElementConverter)` instead.

`SchemaLifecycleAwareElementConverter` extends `ElementConverter` itnerface by adding `open` method to the API.

The info you are looking for is included in java dock of the deprecated method
![image](https://github.com/getindata/flink-http-connector/assets/7932805/2b2cb59d-24a2-4bef-ba02-90996398ba6e)

I see that README and the examples were not updated... sorry :)

**Comment by someshwar1** [comment]
![image](https://github.com/getindata/flink-http-connector/assets/12858939/1d5f287f-75cb-431a-a32b-0c2692062e09)
after updating i am getting compilation issue , added dependencies
org.apache.flink.flink-java
org.apache.flink.flink-clients
org.apache.flink.flink-connector-base

can you please suggest

**Comment by someshwar1** [comment]
![image](https://github.com/getindata/flink-http-connector/assets/12858939/1d5f287f-75cb-431a-a32b-0c2692062e09)
after updating i am getting compilation issue , added dependencies
org.apache.flink.flink-java
org.apache.flink.flink-clients
org.apache.flink.flink-connector-base

can you please suggest

**Comment by kristoffSC** [comment]
The `SchemeLifecycleElementConverter` is no longer a functional interface hence you cannot use lambda expression to represent it.

What you can do is implement the interface and pass its instance or use anonymous class like so:
```
private final SchemaLifecycleAwareElementConverter<String, HttpSinkRequestEntry>
        ELEMENT_CONVERTER_V2 = new SchemaLifecycleAwareElementConverter<>() {
            @Override
            public void open(InitContext context) {
                //noOp
            }

            @Override
            public HttpSinkRequestEntry apply(String element, Context context) {
                return new HttpSinkRequestEntry("POST", element.getBytes(StandardCharsets.UTF_8));
            }
        };

   HttpSink.<String>builder().setElementConverter(ELEMENT_CONVERTER_V2)...
```

The `open` method is called when SinkWriter is created.

**Comment by someshwar1** [comment]
Thank @kristoffSC for suggestion, i have tried it out getting serialize issue 

Caused by: org.apache.flink.streaming.runtime.tasks.StreamTaskException: Could not serialize object for key serializedUDF.

**Comment by someshwar1** [comment]
> functional interf

found issue 
instead implement SchemaLifecycleAwareElementConverter  in same class created new class and call as shown below fixed the issue


public class ElementConverterCustom implements SchemaLifecycleAwareElementConverter<String, HttpSinkRequestEntry>{

    @Override
    public void open(InitContext context) {
      //noOp
    }

    @Override
    public HttpSinkRequestEntry apply(String element, Context context) {
      return new HttpSinkRequestEntry("GET", element.getBytes(StandardCharsets.UTF_8));
    }
  }
 



var httpSink = HttpSink.<String>builder()
    .setEndpointUrl("("http://example.com/myendpoint")
    .setElementConverter(
       **new  ElementConverterCustom()**)
    .setSinkHttpClientBuilder(JavaNetSinkHttpClient::new)
    .setProperty(
        HttpConnectorConfigConstants.SINK_HEADER_PREFIX + "Content-Type",
        contentTypeHeader)
           .build();

**Comment by kristoffSC** [comment]
Glad that worked, seems like straight forward Java <-> Flink case :)

> instead implement SchemaLifecycleAwareElementConverter in same class

This will work but your "new inner class" must be declared static. If its not `static` then it holds an reference to the "outer" class which is not serializable.

Also if you use an Anonymous class  this will also work if defined in the same class.

Anyways the options are:
1. use static class or anonymous class if you wish to define `SchemaLifecycleAwareElementConverter` as inner class
2. implement `SchemaLifecycleAwareElementConverter` on a brand new class.
