### ISSUE TITLE
Check Flink 1.17 compatibility

### ISSUE THREAD

**Issue by kristoffSC** [getindata/flink-http-connector#64]
Run connector on Flink 1.17
Add build configuration for 1.17
Update Readme.md

In case of bigger issues with 1.15, drop the support for it.

**Comment by davidradl** [comment]
I tried to compile against 1.17 and 1.18 and get a compile error:
```
There was an error in the forked process
TestEngine with ID 'junit-jupiter' failed to discover tests
```

**Comment by kristoffSC** [comment]
yep, I had exact same thing. Hence the ticket.
I've not spend a lot of time on this one but it seems there is some dependency issue around Junit libs...
Something is drag along with Flink libraries.

**Comment by davidradl** [comment]
I have run the tests locally at the latest main and see 
`[ERROR] Tests run: 257, Failures: 3, Errors: 15, Skipped: 0`

Inspired by[https://blog.jetbrains.com/idea/2020/08/migrating-from-junit-4-to-junit-5/]( https://blog.jetbrains.com/idea/2020/08/migrating-from-junit-4-to-junit-5/ ) I amended the pom file to use  junit5, this allows tests to run at 1.15, 1.16, 1.17, 1.18.0, 1.18.1

at 1.18.1 there are a couple more errors.

**Comment by davidradl** [comment]
@kristoffSC I have added junit 5 support so the junts run at Flink 1.17 and 1.18.

Note there are errors

**Comment by davidradl** [comment]
@kristoffSC I see 1.15.0 is failing to build on the pr, but 1.15.3 works. If we drop 1.15 this will not be an issue

**Comment by davidradl** [comment]
@kristoffSC Any idea why the pr build jobs are being cancelled?
