### ISSUE TITLE
Possible to merge http request params with http response params?

### ISSUE THREAD

**Issue by awakelee** [getindata/flink-http-connector#65]
For example:
```
CREATE TABLE Customers (
    id STRING,
    id2 STRING,
    msg STRING,
    uuid STRING,
    details ROW<
      isActive BOOLEAN,
      nestedDetails ROW<
        balance STRING
      >
    >
) WITH (
'connector' = 'rest-lookup'
)
```
```
CREATE TABLE Orders (
    id STRING,
    id2 STRING,
    proc_time AS PROCTIME()
) WITH (
'connector' = 'datagen'
);
```

I need the require param id and id2 from  table Customers instead of  Orders:
```
SELECT c.id, c.id2, c.msg, c.uuid, c.isActive, c.balance FROM Orders AS o 
JOIN Customers FOR SYSTEM_TIME AS OF o.proc_time AS c ON o.id = c.id AND o.id2 = c.id2
```

I find that `com.getindata.connectors.http.internal.table.lookup.JavaNetHttpPollingClient#processHttpResponse` just parse http response data to RowData. If the response data does not contain id or id2, the RowData returned will contains null column.

**Comment by kristoffSC** [comment]
Hi @awakelee will this not work?

SELECT o.id, o.id2, c.msg, c.uuid, c.isActive, c.balance FROM Orders AS o 
JOIN Customers FOR SYSTEM_TIME AS OF o.proc_time AS c ON o.id = c.id AND o.id2 = c.id2

**Comment by kristoffSC** [comment]
Sorry, I dont think I understand what seems to be a problem here?

> if the response data does not contain id or id2, the RowData returned will contains null column.

yes, what else would you want to have under c.id and c.id2 if not values returned by the external system? If the external system returned null for those values, this is what will you have.

> JavaNetHttpPollingClient#processHttpResponse just parse http response data to RowData.

Exactly, this is its soil purpose.

**Comment by kristoffSC** [comment]
Hi @awakelee 
Very sorry about the wait.
To be honest I don't think I understand what seems to be a problem here.

> if the response data does not contain id or id2, the RowData returned will contains null column.

yes, what else would you want to have under c.id and c.id2 if not values returned by the external system? If the external system returned null for those values, this is what will you have.

> JavaNetHttpPollingClient#processHttpResponse just parse http response data to RowData.

Exactly, this is its soil purpose.
