### ISSUE TITLE
junit failures 

### ISSUE THREAD

**Issue by davidradl** [getindata/flink-http-connector#73]
Running at a Flink 1.15 there are 3 errors running at Flink 1.18 there are 5 errors   

The 1.18 errors are

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   HttpSinkConnectionTest.testFailedConnection:238 expected: <1> but was: <0>
[ERROR]   HttpSinkConnectionTest.testServerErrorConnection:202 expected: <1> but was: <0>
[ERROR]   JavaNetHttpPollingClientConnectionTest.shouldHandleCodeBasedOnConfiguration:208 
expected: false
 but was: true
[ERROR]   JavaNetHttpPollingClientConnectionTest.shouldHandleCodeBasedOnConfiguration:208 
expected: true
 but was: false
[ERROR]   JavaNetHttpPollingClientConnectionTest.shouldHandleServerError:222 Expected at least one request matching: {
  "method" : "ANY"
}
Requests received: [ ]
[ERROR] Errors: 
[ERROR]   JavaNetHttpPollingClientConnectionTest.shouldConnectWithBasicAuth:269 » NoSuchElement
[ERROR]   JavaNetHttpPollingClientConnectionTest.shouldConnectWithBasicAuth:269 » NoSuchElement
[ERROR]   JavaNetHttpPollingClientConnectionTest.shouldQuery200WithBodyParams:159 » NoSuchElement
[ERROR]   JavaNetHttpPollingClientConnectionTest.shouldQuery200WithBodyParams:159 » NoSuchElement
[ERROR]   JavaNetHttpPollingClientConnectionTest.shouldQuery200WithParams:129 » NoSuchElement

**Comment by kristoffSC** [comment]
Hi, if we will drop 1.15 and remove all 1.15 dependencies from the code will we have still those errors?
We can drop 1.15 anyways though.

**Comment by davidradl** [comment]
this is fixed by https://github.com/getindata/flink-http-connector/pull/72
