### ISSUE TITLE
Provide optional query parameters along with the body payload.

### ISSUE THREAD

**Issue by OlivierZembri** [getindata/flink-http-connector#78]
For body-based requests, the current connector supports either query parameters or body parameters but not a mix of both.

Some REST API require query parameters like ?version=123&id=1 or an apiKey as query parameter in addition to the body payload.

**Comment by kristoffSC** [comment]
Hi @OlivierZembri 
Thank you for submitting this issue and preparing the PR. 

I'm taking look at it.

**Comment by kristoffSC** [comment]
Released in 0.12.0.
Version is already pushed to maven central. It usually takes some time until it will be visible on connector's maven page but it should be available to download from maven already
