### ISSUE TITLE
HTTP-92 Customization of HTTP lookup source logger

### ISSUE THREAD

**Issue by OlivierZembri** [getindata/flink-http-connector#92]
The documentation related to [Custom request/response callback](https://github.com/getindata/flink-http-connector?tab=readme-ov-file#custom-requestresponse-callback) states that the default SLF4J logger can be overridden by a custom implementation for HttpSink.

There is no such mechanism in place to override the default SLF4J logger for used for HTTP lookup source connector.

This mechanism would be quite useful to change the verbosity of the message and the level at which they are logged thereby avoiding leak of sensible information conveyed by processed events for example.

**Comment by AdrianVasiliu** [comment]
@kristoffSC @grzegorz8 For enterprise usages, this is a critical need regarding data protection policy. Could you please review, and, if you'll agree with the PR, release a new version to include the new capability?

**Comment by kristoffSC** [comment]
@OlivierZembri 
Thank you for this contribution, the time and effort you putted into it. I have merge it to master.

**Comment by OlivierZembri** [comment]
@kristoffSC 
Thanks for merging this PR. In order to consume this new capability, we would need a new release 0.14.0.
Have you planned to trigger a build for it ?

**Comment by AdrianVasiliu** [comment]
@kristoffSC Thanks a lot! 
Could you please release this (in 0.14.0)? 
Please don't wait for some other PR to be merged, we need this very urgently... 
cc @grzegorz8

**Comment by AdrianVasiliu** [comment]
@kristoffSC The release seems still unavailable in the maven repo. Can we hope for a short-term solution?

**Comment by AdrianVasiliu** [comment]
@kristoffSC Great, happy about both news, thanks a lot :-) 
I suppose the availability on maven will take a bit of more time (on maven repo side), for now the artifact isn't yet available.

**Comment by AdrianVasiliu** [comment]
It works now :-) All good, thanks!
